

spring:
  application.name: dumptabase

  datasource:
    platform: h2 #values: hsqldb, h2, oracle, mysql, postgressql
    schema: dumptabase-sample
    username: root
    password: root

  h2.console:
    enabled: true
    path: /h2-console

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop #values: create-drop, create, update, validate, none
